<?php

/**
 * CalendarEvent
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    kuepa
 * @subpackage model
 * @author     fiberbunny
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class CalendarEvent extends BaseCalendarEvent
{
    CONST TIPO_REF_PROFILE = 'PROFI';
    CONST TIPO_REF_COURSE  = 'COURS';
    CONST TIPO_REF_TUTORIA = 'CLASS';
        
    /**
     * 
     * @return CalendarEventTable
     */
    public static function getRepository() {
        return Doctrine_Core::getTable('CalendarEvent');
    }
}
