<?php

/**
 * CalendarEventTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CalendarEventTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CalendarEventTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CalendarEvent');
    }
}