<?php

/**
 * Chapter
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    kuepa
 * @subpackage model
 * @author     fiberbunny
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Chapter extends BaseChapter {
	const TYPE = 'Chapter';

    /**
     * 
     * @return CourseTable
     */
    public static function getRepository() {
        return Doctrine_Core::getTable('Chapter');
    }

    public function getLessons(){
    	return ChapterService::getInstance()->getLessonsList($this->getId());
    }

    public function getLastResourceViewed($profile_id){
        return LogService::getInstance()->getLastResourceIdViewed($profile_id, $this);
    }

    public function getTotalTime($profile_id){
        return LogService::getInstance()->getTotalTime($profile_id, $this);
    }

}
