<?php

/**
 * ChapterTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ChapterTable extends ComponentTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object ChapterTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Chapter');
    }

    public function getChaptersForCourse($course_id) {
        $query = $this->createQuery('c')
                    ->innerJoin('c.LearningPath lp ON c.id = lp.child_id')
                    ->where('lp.parent_id = ?', $course_id)
                    ->orderBy("lp.position asc");

        return $query->execute();
    }
}