<?php

/**
 * ChapterHasLessonViewTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ChapterHasLessonViewTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ChapterHasLessonViewTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ChapterHasLessonView');
    }
}