<?php

/**
 * CollegeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CollegeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CollegeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('College');
    }
}