<?php

/**
 * CollegeLearningPathTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CollegeLearningPathTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CollegeLearningPathTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CollegeLearningPath');
    }
}