<?php

/**
 * Component
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    kuepa
 * @subpackage model
 * @author     fiberbunny
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Component extends BaseComponent
{
    /**
     * 
     * @return ComponentTable
     */
    public static function getRepository() {
        return Doctrine_Core::getTable('Component');
    }
    
    public function getThumbnailPath() {
        return sfConfig::get('app_image_path_component') . $this->getThumbnail();
    }
    
    public function getChildren() {
        $query = Component::getRepository()->createQuery('c')
                    ->innerJoin('c.LearningPath lp ON c.id = lp.child_id')
                    ->where('lp.parent_id = ?', $this->getId())
                    ->orderBy("lp.position asc");

        return $query->execute();
    }
    
    public function __toString() {
        return get_called_class();
    }

    public function getNameSlug(){
        return self::slugify($this->name);
    }

    public static function slugify($text)
    {
        // replace all non letters or digits by -
        $text = preg_replace('/\W+/', '-', $text);
     
        // trim and lowercase
        $text = strtolower(trim($text, '-'));
     
        return $text;
    }
}
