<?php

/**
 * CourseTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CourseTable extends ComponentTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object CourseTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Course');
    }
    
    public function getCoursesForUser($profile_id, $college_id = null, $status = array()) {
        $query = $this->createQuery('c')
                      ->innerJoin('c.ProfileLearningPath plp')
                      ->where('plp.profile_id = ?', $profile_id);

        if($college_id){
            $query->innerJoin("c.CollegeLearningPath clp")
                  ->andWhere("clp.college_id = ?", $college_id);
        }

        if(count($status)){
            $query->andWhereIn("plp.profile_learning_path_status_id",$status);
        }

        return $query->execute();
    }

    
    public function getCoursesForCollege($college_id) {
        
        $query = $this->createQuery('c')
                    ->innerJoin('c.CollegeLearningPath clp')
                    ->where('clp.college_id = ?', $college_id);
        
        $query->useResultCache(true, null, cacheHelper::getInstance()->genKey('Course_getCoursesForCollege', array($college_id)) );
        
        return $query->execute();
    }
}