<?php

/**
 * CourseTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CourseTable extends ComponentTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object CourseTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Course');
    }
    
    public function getChaptersForUser($profile_id) {
        $query = $this->createQuery('c');
        $query->addWhere('c.Profiles.id = ?', $profile_id);
        
        return $query->execute();
    }
}