<?php

/**
 * CourseHasChapterViewTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CourseHasChapterViewTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CourseHasChapterViewTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CourseHasChapterView');
    }
}