<?php

/**
 * DependencyExercisePathTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DependencyExercisePathTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DependencyExercisePathTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DependencyExercisePath');
    }
}