<?php

/**
 * ExerciseQuestionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ExerciseQuestionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ExerciseQuestionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ExerciseQuestion');
    }
}