<?php

/**
 * ExerciseAttempTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ExerciseAttempTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ExerciseAttempTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ExerciseAttemp');
    }
}