<?php

/**
 * ExerciseTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ExerciseTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ExerciseTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Exercise');
    }
}