<?php

/**
 * ExerciseAnswerItemTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ExerciseAnswerItemTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ExerciseAnswerItemTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ExerciseAnswerItem');
    }
}