<?php

/**
 * ExerciseAnswerTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ExerciseAnswerTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ExerciseAnswerTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ExerciseAnswer');
    }
}