<?php

/**
 * ExerciseHasExerciseQuestionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ExerciseHasExerciseQuestionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ExerciseHasExerciseQuestionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ExerciseHasExerciseQuestion');
    }
}