<?php

/**
 * FlashMessageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FlashMessageTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FlashMessageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('FlashMessage');
    }
}