<?php

/**
 * GroupCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GroupCategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GroupCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('GroupCategory');
    }
}