<?php

/**
 * GroupSubGroupTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GroupSubGroupTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GroupSubGroupTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('GroupSubGroup');
    }
}