<?php

/**
 * Groups
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    kuepa
 * @subpackage model
 * @author     kibind
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Groups extends BaseGroups
{
    /**
    * 
    * @return Groups
    */
    public static function getRepository() {
        return Doctrine_Core::getTable('Groups');
    }


    public function __toString(){
        return $this->getId() . " - " . $this->getName();
    }

}
