<?php

/**
 * GroupProfileTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GroupProfileTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GroupProfileTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('GroupProfile');
    }
}