<?php

/**
 * LearningPath
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    kuepa
 * @subpackage model
 * @author     fiberbunny
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class LearningPath extends BaseLearningPath {

    /**
     * 
     * @return LessonTable
     */
    public static function getRepository() {
        return Doctrine_Core::getTable('LearningPath');
    }
    
    public function preSave($event)   {
        $this->clearCache($event);
    }
    
    public function preDelete($event) {
        $this->clearCache($event);
    }
    
    public function clearCache($event)
    {
        CacheHelper::getInstance()->deleteByPrefix('Component_getChilds', array( $this->getParentId() ));
    }

}
