<?php

/**
 * LearningWayTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LearningWayTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LearningWayTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('LearningWay');
    }
}