<?php

/**
 * LearningPathTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LearningPathTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LearningPathTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('LearningPath');
    }
}