<?php

/**
 * LearningPathViewTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LearningPathViewTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LearningPathViewTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('LearningPathView');
    }
}