<?php

/**
 * LessonHasResourceViewTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LessonHasResourceViewTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LessonHasResourceViewTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('LessonHasResourceView');
    }
}