<?php

/**
 * LessonTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LessonTable extends ComponentTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object LessonTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Lesson');
    }

    public function getLessonsForChapters($chapter_id) {
        $query = $this->createQuery('c')
                    ->innerJoin('c.LearningPath lp ON c.id = lp.child_id')
                    ->where('lp.parent_id = ?', $chapter_id)
                    ->orderBy("lp.position asc");

        return $query->execute();
    }
}