<?php

/**
 * LessonTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LessonTable extends ComponentTable {

    /**
     * Returns an instance of this class.
     *
     * @return object LessonTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('Lesson');
    }

}