<?php

/**
 * LogAccessTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LogAccessTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LogAccessTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('LogAccess');
    }
}