<?php

/**
 * LoginTokenTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LoginTokenTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LoginTokenTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('LoginToken');
    }
}