<?php

/**
 * LogViewComponentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LogViewComponentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LogViewComponentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('LogViewComponent');
    }
}