<?php

/**
 * LogViewComponent
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    kuepa
 * @subpackage model
 * @author     fiberbunny
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class LogViewComponent extends BaseLogViewComponent
{
	public static function getRepository() {
        return Doctrine_Core::getTable('LogViewComponent');
    }

    public function __toString(){
    	$time = $this->getCreatedAt();
    	return $this->getComponent()->getName();
    }

    public function getLapse(){
    	return (strtotime($this->updated_at) - strtotime($this->created_at));
    }

    public function isSkim(){
        return $this->getLapse() < 10;
    }
}
