<?php

/**
 * MailMessage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    kuepa
 * @subpackage model
 * @author     kibind
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class MailMessage extends BaseMailMessage
{
  
  static public function getRepository(){
    return(Doctrine_Core::getTable('MailMessage'));
  }

  public function getPriorities(){
    return(array("1","2","3","4","5"));
  }
}
