<?php

/**
 * MessageRecipientTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MessageRecipientTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MessageRecipientTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MessageRecipient');
    }
}