<?php

/**
 * NotificationActionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NotificationActionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object NotificationActionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('NotificationAction');
    }
}