<?php

/**
 * ProfileViewFlashMessageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProfileViewFlashMessageTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProfileViewFlashMessageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProfileViewFlashMessage');
    }
}