<?php

/**
 * ProfileComponentCompletedStatusTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProfileComponentCompletedStatusTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProfileComponentCompletedStatusTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProfileComponentCompletedStatus');
    }
}