<?php

/**
 * ProfileCollegeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProfileCollegeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProfileCollegeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProfileCollege');
    }
}