<?php

/**
 * ProfileTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProfileTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProfileTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Profile');
    }
    public function listComponents(){
        /*
        $idProfile = sfContext::getInstance()->getUser()->getProfile()->getId();
        $q = $this->createQuery('p')
             ->leftJoin('p.Component c')
             ->select('p.*, c.*')
             ->where('p.profile_id = ?', $idProfile);
        return $q->execute();
         * 
         */
    }
}