<?php

/**
 * ProfileHasGroupTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProfileHasGroupTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProfileHasGroupTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProfileHasGroup');
    }
}