<?php

/**
 * ProfileHasLearningWayTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProfileHasLearningWayTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProfileHasLearningWayTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProfileHasLearningWay');
    }
}