<?php

/**
 * Profile
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    kuepa
 * @subpackage model
 * @author     fiberbunny
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Profile extends BaseProfile
{
	/**
     * 
     * @return ProfileTable
     */
    public static function getRepository() {
        return Doctrine_Core::getTable('Profile');
    }

    public function getFirstAccess(){
    	return LogService::getInstance()->getFirstAccess($this->getId());
    }

    public function getLastAccess(){
    	return LogService::getInstance()->getLastAccess($this->getId());
    }

    public function getTotalTime($component = null){
    	return LogService::getInstance()->getTotalTime($this->getId(), $component);
    }

    public function getTotalRecourseViewed(){
    	return LogService::getInstance()->getTotalRecourseViewed($this->getId());
    }
}
