<?php

/**
 * ProfileLearningPathTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProfileLearningPathTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProfileLearningPathTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProfileLearningPath');
    }
    
    public function getCoursesArrayByIdProfile($idProfile)
    {
        $q = $this->createQuery('plp')
             ->select('plp.component_id')
             ->where('plp.profile_id = ?', $idProfile);
        
        return $q->execute(array(),Doctrine::HYDRATE_SCALAR);
    }
}