<?php

/**
 * ProfileLearningPathStatusTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProfileLearningPathStatusTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProfileLearningPathStatusTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProfileLearningPathStatus');
    }
}