<?php

/**
 * RegisterCodeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RegisterCodeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RegisterCodeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RegisterCode');
    }
}