<?php

/**
 * ResourceDataEmbeddedWebTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ResourceDataEmbeddedWebTable extends ResourceDataTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object ResourceDataEmbeddedWebTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ResourceDataEmbeddedWeb');
    }
}