<?php

/**
 * ResourceDataTextTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ResourceDataTextTable extends ResourceDataTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object ResourceDataTextTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ResourceDataText');
    }
}