<?php

/**
 * ResourceDataDocumentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ResourceDataDocumentTable extends ResourceDataTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object ResourceDataDocumentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ResourceDataDocument');
    }
}