<?php

/**
 * ResourceDataTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ResourceDataTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ResourceDataTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ResourceData');
    }
}