<?php

/**
 * ResourceDataExerciseTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ResourceDataExerciseTable extends ResourceDataTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object ResourceDataExerciseTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ResourceDataExercise');
    }
}