<?php

/**
 * ResourceDataVideoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ResourceDataVideoTable extends ResourceDataTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object ResourceDataVideoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ResourceDataVideo');
    }
}