<?php

/**
 * TimeViewComponentByDayTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TimeViewComponentByDayTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TimeViewComponentByDayTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TimeViewComponentByDay');
    }
}