<?php

/**
 * VideoSessionParticipantTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VideoSessionParticipantTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object VideoSessionParticipantTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('VideoSessionParticipant');
    }
}