<?php

/**
 * VideoSessionParticipant
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    kuepa
 * @subpackage model
 * @author     CristalMedia
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class VideoSessionParticipant extends BaseVideoSessionParticipant {

    /**
     *
     * @return type
     */
    public static function getRepository() {
        return Doctrine_Core::getTable('VideoSessionParticipant');
    }

    public static function findByVideoSessionAndProfileId($video_session_id, $profile_id) {
        $q = self::getRepository()->createQuery()
            ->from('VideoSessionParticipant')
            ->where('video_session_id = ? AND profile_id = ?', array($video_session_id, $profile_id));

        return $q->limit(1)->execute()->getFirst();
    }

}
