<?php

/**
 * VideoSession
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    kuepa
 * @subpackage model
 * @author     fiberbunny
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class VideoSession extends BaseVideoSession {
    public static function getRepository() {
        return Doctrine_Core::getTable('VideoSession');
    }
}
