<?php

/**
 * ViewLessonHasResourceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ViewLessonHasResourceTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ViewLessonHasResourceTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ViewLessonHasResource');
    }
}