<?php

/**
 * ViewCourseHasChapterTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ViewCourseHasChapterTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ViewCourseHasChapterTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ViewCourseHasChapter');
    }
}