<?php

/**
 * ViewChapterHasLessonTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ViewChapterHasLessonTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ViewChapterHasLessonTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ViewChapterHasLesson');
    }
}