<?php

/**
 * ViewLearningPathTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ViewLearningPathTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ViewLearningPathTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ViewLearningPath');
    }
}