# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: home, action: index }

lesson_view:
  url: /lesson/view/:course_id/:chapter_id/:lesson_id
  param: { module: lesson, action: index}

lesson_view_resource:
  url: /lesson/view/:course_id/:chapter_id/:lesson_id/:resource_id
  param: { module: lesson, action: index}

exercise_list:
  url: /course/:course_id/exercises
  param: { module: exercise, action: list}

exercise_new:
  url: /lesson/:lesson_id/exercises/new
  param: { module: exercise, action: edit }

exercise_edit:
  url: /exercises/:exercise_id
  param: { module: exercise, action: edit }

sf_guard_signin:
  url:   /login
  param: { module: sfGuardAuth, action: signin }

video_session:
  url: /tutorias
  param: { module: video_session, action: index }

sf_guard_signout:
  url:   /logout
  param: { module: sfGuardAuth, action: signout }

sf_guard_password:
  url:   /request_password
  param: { module: sfGuardAuth, action: password }

account_expired:
  url:  /account/expired
  param: { module: public, action: accountexpired }

messages:
  url: /messages
  param: { module: message, action: index }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
