# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# course
course_api:
  class: RESTRouteCollection
  options:
    module: course
    
# chapter
chapter_api:
  class: RESTRouteCollection
  options:
    module: chapter
    
# lesson
lesson_api:
  class: RESTRouteCollection
  options:
    module: lesson
    
learning_path_delete:
  url: /learning_path/:parent_id/:child_id
  class: sfRequestRoute
  param: { module: learning_path, action: delete }
  requirements:
    parent_id: \d+
    child_id: \d+
    sf_method: [delete]
    
default:
  url:   /*
  params: { module: default, action: notImplemented }
  