<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addlearningpath extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('learning_path', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => 8,
              'autoincrement' => true,
              'primary' => true,
             ),
             'parent_id' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'child_id' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'position' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('learning_path');
    }
}