<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addprofilecomponentcompletedstatus extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('profile_component_completed_status', array(
             'profile_id' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'length' => 8,
             ),
             'component_id' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'length' => 8,
             ),
             'completed_status' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'profile_id',
              1 => 'component_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('profile_component_completed_status');
    }
}