<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addcomponent extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('component', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'autoincrement' => true,
              'length' => 8,
             ),
             'node_id' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'name' => 
             array(
              'type' => 'varchar',
              'length' => 255,
             ),
             'thumbnail' => 
             array(
              'type' => 'varchar',
              'length' => 255,
             ),
             'description' => 
             array(
              'type' => 'text',
              'length' => NULL,
             ),
             'level' => 
             array(
              'type' => 'enum',
              'values' => 
              array(
              0 => 'beginner',
              1 => 'intermediate',
              2 => 'advance',
              ),
              'length' => NULL,
             ),
             'profile_id' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'color' => 
             array(
              'type' => 'enum',
              'values' => 
              array(
              0 => 'green',
              1 => 'lightgreen',
              2 => 'violet',
              3 => 'red',
              4 => 'purple',
              5 => 'blue',
              6 => 'lightblue',
              7 => 'darkblue',
              8 => 'orange',
              ),
              'length' => NULL,
             ),
             'duration' => 
             array(
              'type' => 'float',
              'length' => NULL,
             ),
             'type' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'created_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             'updated_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             'deleted_at' => 
             array(
              'notnull' => false,
              'type' => 'timestamp',
              'length' => 25,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('component');
    }
}