<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addcalendarevent extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('calendar_event', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'autoincrement' => true,
              'length' => 8,
             ),
             'profile_id' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'component_id' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'title' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'description' => 
             array(
              'type' => 'string',
              'length' => NULL,
             ),
             'start' => 
             array(
              'type' => 'timestamp',
              'length' => 25,
             ),
             'end' => 
             array(
              'type' => 'timestamp',
              'length' => 25,
             ),
             'created_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             'updated_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('calendar_event');
    }
}