<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addprofilecollege extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('profile_college', array(
             'profile_id' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'length' => 8,
             ),
             'college_id' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'length' => 8,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'profile_id',
              1 => 'college_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('profile_college');
    }
}