<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addexercise extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('exercise', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'autoincrement' => true,
              'length' => 8,
             ),
             'title' => 
             array(
              'type' => 'string',
              'length' => 200,
             ),
             'description' => 
             array(
              'type' => 'text',
              'length' => NULL,
             ),
             'type' => 
             array(
              'type' => 'string',
              'length' => NULL,
             ),
             'max_attemps' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'start_time' => 
             array(
              'type' => 'datetime',
              'length' => NULL,
             ),
             'end_time' => 
             array(
              'type' => 'datetime',
              'length' => NULL,
             ),
             'expired_time' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'random' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'results_disabled' => 
             array(
              'type' => 'boolean',
              'length' => 25,
             ),
             'created_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             'updated_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             'deleted_at' => 
             array(
              'notnull' => false,
              'type' => 'timestamp',
              'length' => 25,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('exercise');
    }
}