<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addexercisehasexercisequestion extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('exercise_has_exercise_question', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => 8,
              'autoincrement' => true,
              'primary' => true,
             ),
             'exercise_id' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'exercise_question_id' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'position' => 
             array(
              'type' => 'integer',
              'notnull' => true,
              'default' => 1,
              'length' => 8,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('exercise_has_exercise_question');
    }
}