<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addexerciseanswer extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('exercise_answer', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'autoincrement' => true,
              'length' => 8,
             ),
             'title' => 
             array(
              'type' => 'string',
              'length' => 200,
             ),
             'comment' => 
             array(
              'type' => 'text',
              'length' => NULL,
             ),
             'value' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'correct' => 
             array(
              'type' => 'boolean',
              'length' => 25,
             ),
             'exercise_question_id' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'created_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             'updated_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             'deleted_at' => 
             array(
              'notnull' => false,
              'type' => 'timestamp',
              'length' => 25,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('exercise_answer');
    }
}