<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version1 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('profile', 'valid_until', 'date', '25', array(
             ));
        $this->addColumn('profile', 'created_at', 'timestamp', '25', array(
             'notnull' => '1',
             ));
        $this->addColumn('profile', 'updated_at', 'timestamp', '25', array(
             'notnull' => '1',
             ));
        $this->addColumn('profile', 'deleted_at', 'timestamp', '25', array(
             'notnull' => '',
             ));

        $this->addColumn('learning_path', 'enabled', 'tinyint', '1', array(
             'notnull' => '',
             ));
    }

    public function down()
    {
        $this->removeColumn('profile', 'valid_until');
        $this->removeColumn('profile', 'created_at');
        $this->removeColumn('profile', 'updated_at');
        $this->removeColumn('profile', 'deleted_at');
        $this->removeColumn('learning_path', 'enabled');
    }
}