<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version4 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('college_learning_path', 'college_learning_path_component_id_component_id', array(
             'name' => 'college_learning_path_component_id_component_id',
             'local' => 'component_id',
             'foreign' => 'id',
             'foreignTable' => 'component',
             ));
        $this->createForeignKey('college_learning_path', 'college_learning_path_college_id_college_id', array(
             'name' => 'college_learning_path_college_id_college_id',
             'local' => 'college_id',
             'foreign' => 'id',
             'foreignTable' => 'college',
             ));
        $this->addIndex('college_learning_path', 'college_learning_path_component_id', array(
             'fields' => 
             array(
              0 => 'component_id',
             ),
             ));
        $this->addIndex('college_learning_path', 'college_learning_path_college_id', array(
             'fields' => 
             array(
              0 => 'college_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('college_learning_path', 'college_learning_path_component_id_component_id');
        $this->dropForeignKey('college_learning_path', 'college_learning_path_college_id_college_id');
        $this->removeIndex('college_learning_path', 'college_learning_path_component_id', array(
             'fields' => 
             array(
              0 => 'component_id',
             ),
             ));
        $this->removeIndex('college_learning_path', 'college_learning_path_college_id', array(
             'fields' => 
             array(
              0 => 'college_id',
             ),
             ));
    }
}