<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version5 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('register_code', array(
             'id' => 
             array(
              'type' => 'string',
              'primary' => '1',
              'length' => '50',
             ),
             'profile_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'valid_from' => 
             array(
              'type' => 'date',
              'length' => '25',
             ),
             'valid_until' => 
             array(
              'type' => 'date',
              'length' => '25',
             ),
             'valid_days' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'college_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'active' => 
             array(
              'type' => 'boolean',
              'default' => '0',
              'notnull' => '1',
              'length' => '25',
             ),
             'in_use' => 
             array(
              'type' => 'integer',
              'default' => '0',
              'notnull' => '1',
              'length' => '8',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
        $this->createTable('register_code_has_course', array(
             'register_code' => 
             array(
              'type' => 'string',
              'primary' => '1',
              'length' => '50',
             ),
             'course_id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'length' => '8',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'register_code',
              1 => 'course_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('register_code');
        $this->dropTable('register_code_has_course');
    }
}