<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version6 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('register_code', 'register_code_profile_id_profile_id', array(
             'name' => 'register_code_profile_id_profile_id',
             'local' => 'profile_id',
             'foreign' => 'id',
             'foreignTable' => 'profile',
             ));
        $this->createForeignKey('register_code', 'register_code_college_id_college_id', array(
             'name' => 'register_code_college_id_college_id',
             'local' => 'college_id',
             'foreign' => 'id',
             'foreignTable' => 'college',
             ));
        $this->createForeignKey('register_code_has_course', 'register_code_has_course_course_id_component_id', array(
             'name' => 'register_code_has_course_course_id_component_id',
             'local' => 'course_id',
             'foreign' => 'id',
             'foreignTable' => 'component',
             ));
        $this->createForeignKey('register_code_has_course', 'register_code_has_course_register_code_register_code_id', array(
             'name' => 'register_code_has_course_register_code_register_code_id',
             'local' => 'register_code',
             'foreign' => 'id',
             'foreignTable' => 'register_code',
             ));
        $this->addIndex('register_code', 'register_code_profile_id', array(
             'fields' => 
             array(
              0 => 'profile_id',
             ),
             ));
        $this->addIndex('register_code', 'register_code_college_id', array(
             'fields' => 
             array(
              0 => 'college_id',
             ),
             ));
        $this->addIndex('register_code_has_course', 'register_code_has_course_course_id', array(
             'fields' => 
             array(
              0 => 'course_id',
             ),
             ));
        $this->addIndex('register_code_has_course', 'register_code_has_course_register_code', array(
             'fields' => 
             array(
              0 => 'register_code',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('register_code', 'register_code_profile_id_profile_id');
        $this->dropForeignKey('register_code', 'register_code_college_id_college_id');
        $this->dropForeignKey('register_code_has_course', 'register_code_has_course_course_id_component_id');
        $this->dropForeignKey('register_code_has_course', 'register_code_has_course_register_code_register_code_id');
        $this->removeIndex('register_code', 'register_code_profile_id', array(
             'fields' => 
             array(
              0 => 'profile_id',
             ),
             ));
        $this->removeIndex('register_code', 'register_code_college_id', array(
             'fields' => 
             array(
              0 => 'college_id',
             ),
             ));
        $this->removeIndex('register_code_has_course', 'register_code_has_course_course_id', array(
             'fields' => 
             array(
              0 => 'course_id',
             ),
             ));
        $this->removeIndex('register_code_has_course', 'register_code_has_course_register_code', array(
             'fields' => 
             array(
              0 => 'register_code',
             ),
             ));
    }
}