<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version8 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('message', 'message_parent_id_message_id', array(
             'name' => 'message_parent_id_message_id',
             'local' => 'parent_id',
             'foreign' => 'id',
             'foreignTable' => 'message',
             ));
        $this->addIndex('message', 'message_parent_id', array(
             'fields' => 
             array(
              0 => 'parent_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('message', 'message_parent_id_message_id');
        $this->removeIndex('message', 'message_parent_id', array(
             'fields' => 
             array(
              0 => 'parent_id',
             ),
             ));
    }
}