<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version9 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->removeColumn('message', 'message');
        $this->addColumn('message', 'content', 'string', '', array(
             ));
    }

    public function down()
    {
        $this->addColumn('message', 'message', 'string', '', array(
             ));
        $this->removeColumn('message', 'content');
    }
}