<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version7 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('message', 'parent_id', 'integer', '8', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('message', 'parent_id');
    }
}