<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version12 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('component', 'deadline', 'date', '25', array(
             ));
        $this->addColumn('profile_learning_path', 'deadline', 'date', '25', array(
             ));
        $this->addColumn('profile_learning_path', 'position', 'integer', '8', array(
             'default' => '0',
             ));
    }

    public function down()
    {
        $this->removeColumn('component', 'deadline');
        $this->removeColumn('profile_learning_path', 'deadline');
        $this->removeColumn('profile_learning_path', 'position');
    }
}