<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version11 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('resource_data', 'word_count', 'integer', '8', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('resource_data', 'word_count');
    }
}