<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version16 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('message', 'message_author_id_profile_id', array(
             'name' => 'message_author_id_profile_id',
             'local' => 'author_id',
             'foreign' => 'id',
             'foreignTable' => 'profile',
             ));
        $this->addIndex('message', 'message_author_id', array(
             'fields' => 
             array(
              0 => 'author_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('message', 'message_author_id_profile_id');
        $this->removeIndex('message', 'message_author_id', array(
             'fields' => 
             array(
              0 => 'author_id',
             ),
             ));
    }
}