<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version18 extends Doctrine_Migration_Base
{
    public function up()
    {
        // $this->dropForeignKey('log_view_component', 'log_view_component_component_id_component_id');
        $this->createForeignKey('log_view_component', 'log_view_component_course_id_component_id', array(
             'name' => 'log_view_component_course_id_component_id',
             'local' => 'course_id',
             'foreign' => 'id',
             'foreignTable' => 'component',
             ));
        $this->createForeignKey('log_view_component', 'log_view_component_chapter_id_component_id', array(
             'name' => 'log_view_component_chapter_id_component_id',
             'local' => 'chapter_id',
             'foreign' => 'id',
             'foreignTable' => 'component',
             ));
        $this->createForeignKey('log_view_component', 'log_view_component_lesson_id_component_id', array(
             'name' => 'log_view_component_lesson_id_component_id',
             'local' => 'lesson_id',
             'foreign' => 'id',
             'foreignTable' => 'component',
             ));
        // $this->createForeignKey('log_view_component', 'log_view_component_resource_id_component_id', array(
        //      'name' => 'log_view_component_resource_id_component_id',
        //      'local' => 'resource_id',
        //      'foreign' => 'id',
        //      'foreignTable' => 'component',
        //      ));
        $this->addIndex('log_view_component', 'log_view_component_course_id', array(
             'fields' => 
             array(
              0 => 'course_id',
             ),
             ));
        $this->addIndex('log_view_component', 'log_view_component_chapter_id', array(
             'fields' => 
             array(
              0 => 'chapter_id',
             ),
             ));
        $this->addIndex('log_view_component', 'log_view_component_lesson_id', array(
             'fields' => 
             array(
              0 => 'lesson_id',
             ),
             ));
        // $this->addIndex('log_view_component', 'log_view_component_resource_id', array(
        //      'fields' => 
        //      array(
        //       0 => 'resource_id',
        //      ),
        //      ));
    }

    public function down()
    {
        // $this->createForeignKey('log_view_component', 'log_view_component_component_id_component_id', array(
        //      'name' => 'log_view_component_component_id_component_id',
        //      'local' => 'component_id',
        //      'foreign' => 'id',
        //      'foreignTable' => 'component',
        //      ));
        $this->dropForeignKey('log_view_component', 'log_view_component_course_id_component_id');
        $this->dropForeignKey('log_view_component', 'log_view_component_chapter_id_component_id');
        $this->dropForeignKey('log_view_component', 'log_view_component_lesson_id_component_id');
        // $this->dropForeignKey('log_view_component', 'log_view_component_resource_id_component_id');
        $this->removeIndex('log_view_component', 'log_view_component_course_id', array(
             'fields' => 
             array(
              0 => 'course_id',
             ),
             ));
        $this->removeIndex('log_view_component', 'log_view_component_chapter_id', array(
             'fields' => 
             array(
              0 => 'chapter_id',
             ),
             ));
        $this->removeIndex('log_view_component', 'log_view_component_lesson_id', array(
             'fields' => 
             array(
              0 => 'lesson_id',
             ),
             ));
        // $this->removeIndex('log_view_component', 'log_view_component_resource_id', array(
        //      'fields' => 
        //      array(
        //       0 => 'resource_id',
        //      ),
        //      ));
    }
}