<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version16 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('college_learning_path', 'deadline', 'date', '25', array(
             ));
        $this->addColumn('college_learning_path', 'position', 'integer', '8', array(
             'default' => '0',
             ));
        $this->addColumn('profile_component_completed_status', 'time_remaining', 'integer', '8', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('college_learning_path', 'deadline');
        $this->removeColumn('college_learning_path', 'position');
        $this->removeColumn('profile_component_completed_status', 'time_remaining');
    }
}