<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version31 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('dependency_exercise_path', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'exercise_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'exercise_question_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'depends_course_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'depends_chapter_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'depends_lesson_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             ), array(
             'indexes' => 
             array(
              'dep_exe_path_unique_pair' => 
              array(
              'fields' => 
              array(
               0 => 'exercise_id',
               1 => 'exercise_question_id',
               2 => 'depends_course_id',
               3 => 'depends_chapter_id',
               4 => 'depends_lesson_id',
              ),
              'type' => 'unique',
              ),
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('dependency_exercise_path');
    }
}