<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version28 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('profile', 'google_id', 'varchar', '45', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('profile', 'google_id');
    }
}