<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version32 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('dependency_exercise_path', 'dependency_exercise_path_exercise_id_exercise_id', array(
             'name' => 'dependency_exercise_path_exercise_id_exercise_id',
             'local' => 'exercise_id',
             'foreign' => 'id',
             'foreignTable' => 'exercise',
             ));
        $this->createForeignKey('dependency_exercise_path', 'deei', array(
             'name' => 'deei',
             'local' => 'exercise_question_id',
             'foreign' => 'id',
             'foreignTable' => 'exercise_question',
             ));
        $this->createForeignKey('dependency_exercise_path', 'dependency_exercise_path_depends_course_id_component_id', array(
             'name' => 'dependency_exercise_path_depends_course_id_component_id',
             'local' => 'depends_course_id',
             'foreign' => 'id',
             'foreignTable' => 'component',
             ));
        $this->createForeignKey('dependency_exercise_path', 'dependency_exercise_path_depends_chapter_id_component_id', array(
             'name' => 'dependency_exercise_path_depends_chapter_id_component_id',
             'local' => 'depends_chapter_id',
             'foreign' => 'id',
             'foreignTable' => 'component',
             ));
        $this->createForeignKey('dependency_exercise_path', 'dependency_exercise_path_depends_lesson_id_component_id', array(
             'name' => 'dependency_exercise_path_depends_lesson_id_component_id',
             'local' => 'depends_lesson_id',
             'foreign' => 'id',
             'foreignTable' => 'component',
             ));
        $this->addIndex('dependency_exercise_path', 'dependency_exercise_path_exercise_id', array(
             'fields' => 
             array(
              0 => 'exercise_id',
             ),
             ));
        $this->addIndex('dependency_exercise_path', 'dependency_exercise_path_exercise_question_id', array(
             'fields' => 
             array(
              0 => 'exercise_question_id',
             ),
             ));
        $this->addIndex('dependency_exercise_path', 'dependency_exercise_path_depends_course_id', array(
             'fields' => 
             array(
              0 => 'depends_course_id',
             ),
             ));
        $this->addIndex('dependency_exercise_path', 'dependency_exercise_path_depends_chapter_id', array(
             'fields' => 
             array(
              0 => 'depends_chapter_id',
             ),
             ));
        $this->addIndex('dependency_exercise_path', 'dependency_exercise_path_depends_lesson_id', array(
             'fields' => 
             array(
              0 => 'depends_lesson_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('dependency_exercise_path', 'dependency_exercise_path_exercise_id_exercise_id');
        $this->dropForeignKey('dependency_exercise_path', 'deei');
        $this->dropForeignKey('dependency_exercise_path', 'dependency_exercise_path_depends_course_id_component_id');
        $this->dropForeignKey('dependency_exercise_path', 'dependency_exercise_path_depends_chapter_id_component_id');
        $this->dropForeignKey('dependency_exercise_path', 'dependency_exercise_path_depends_lesson_id_component_id');
        $this->removeIndex('dependency_exercise_path', 'dependency_exercise_path_exercise_id', array(
             'fields' => 
             array(
              0 => 'exercise_id',
             ),
             ));
        $this->removeIndex('dependency_exercise_path', 'dependency_exercise_path_exercise_question_id', array(
             'fields' => 
             array(
              0 => 'exercise_question_id',
             ),
             ));
        $this->removeIndex('dependency_exercise_path', 'dependency_exercise_path_depends_course_id', array(
             'fields' => 
             array(
              0 => 'depends_course_id',
             ),
             ));
        $this->removeIndex('dependency_exercise_path', 'dependency_exercise_path_depends_chapter_id', array(
             'fields' => 
             array(
              0 => 'depends_chapter_id',
             ),
             ));
        $this->removeIndex('dependency_exercise_path', 'dependency_exercise_path_depends_lesson_id', array(
             'fields' => 
             array(
              0 => 'depends_lesson_id',
             ),
             ));
    }
}