<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version20 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('dependency_path', 'dependency_path_course_id_component_id', array(
             'name' => 'dependency_path_course_id_component_id',
             'local' => 'course_id',
             'foreign' => 'id',
             'foreignTable' => 'component',
             ));
        $this->createForeignKey('dependency_path', 'dependency_path_chapter_id_component_id', array(
             'name' => 'dependency_path_chapter_id_component_id',
             'local' => 'chapter_id',
             'foreign' => 'id',
             'foreignTable' => 'component',
             ));
        $this->createForeignKey('dependency_path', 'dependency_path_lesson_id_component_id', array(
             'name' => 'dependency_path_lesson_id_component_id',
             'local' => 'lesson_id',
             'foreign' => 'id',
             'foreignTable' => 'component',
             ));
        $this->createForeignKey('dependency_path', 'dependency_path_depends_course_id_component_id', array(
             'name' => 'dependency_path_depends_course_id_component_id',
             'local' => 'depends_course_id',
             'foreign' => 'id',
             'foreignTable' => 'component',
             ));
        $this->createForeignKey('dependency_path', 'dependency_path_depends_chapter_id_component_id', array(
             'name' => 'dependency_path_depends_chapter_id_component_id',
             'local' => 'depends_chapter_id',
             'foreign' => 'id',
             'foreignTable' => 'component',
             ));
        $this->createForeignKey('dependency_path', 'dependency_path_depends_lesson_id_component_id', array(
             'name' => 'dependency_path_depends_lesson_id_component_id',
             'local' => 'depends_lesson_id',
             'foreign' => 'id',
             'foreignTable' => 'component',
             ));
        $this->addIndex('dependency_path', 'dependency_path_course_id', array(
             'fields' => 
             array(
              0 => 'course_id',
             ),
             ));
        $this->addIndex('dependency_path', 'dependency_path_chapter_id', array(
             'fields' => 
             array(
              0 => 'chapter_id',
             ),
             ));
        $this->addIndex('dependency_path', 'dependency_path_lesson_id', array(
             'fields' => 
             array(
              0 => 'lesson_id',
             ),
             ));
        $this->addIndex('dependency_path', 'dependency_path_depends_course_id', array(
             'fields' => 
             array(
              0 => 'depends_course_id',
             ),
             ));
        $this->addIndex('dependency_path', 'dependency_path_depends_chapter_id', array(
             'fields' => 
             array(
              0 => 'depends_chapter_id',
             ),
             ));
        $this->addIndex('dependency_path', 'dependency_path_depends_lesson_id', array(
             'fields' => 
             array(
              0 => 'depends_lesson_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('dependency_path', 'dependency_path_course_id_component_id');
        $this->dropForeignKey('dependency_path', 'dependency_path_chapter_id_component_id');
        $this->dropForeignKey('dependency_path', 'dependency_path_lesson_id_component_id');
        $this->dropForeignKey('dependency_path', 'dependency_path_depends_course_id_component_id');
        $this->dropForeignKey('dependency_path', 'dependency_path_depends_chapter_id_component_id');
        $this->dropForeignKey('dependency_path', 'dependency_path_depends_lesson_id_component_id');
        $this->removeIndex('dependency_path', 'dependency_path_course_id', array(
             'fields' => 
             array(
              0 => 'course_id',
             ),
             ));
        $this->removeIndex('dependency_path', 'dependency_path_chapter_id', array(
             'fields' => 
             array(
              0 => 'chapter_id',
             ),
             ));
        $this->removeIndex('dependency_path', 'dependency_path_lesson_id', array(
             'fields' => 
             array(
              0 => 'lesson_id',
             ),
             ));
        $this->removeIndex('dependency_path', 'dependency_path_depends_course_id', array(
             'fields' => 
             array(
              0 => 'depends_course_id',
             ),
             ));
        $this->removeIndex('dependency_path', 'dependency_path_depends_chapter_id', array(
             'fields' => 
             array(
              0 => 'depends_chapter_id',
             ),
             ));
        $this->removeIndex('dependency_path', 'dependency_path_depends_lesson_id', array(
             'fields' => 
             array(
              0 => 'depends_lesson_id',
             ),
             ));
    }
}