<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version30 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('video_session', 'video_session_profile_id_profile_id', array(
             'name' => 'video_session_profile_id_profile_id',
             'local' => 'profile_id',
             'foreign' => 'id',
             'foreignTable' => 'profile',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('video_session', 'video_session_student_profile_id_profile_id', array(
             'name' => 'video_session_student_profile_id_profile_id',
             'local' => 'student_profile_id',
             'foreign' => 'id',
             'foreignTable' => 'profile',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('video_session', 'video_session_chapter_id_component_id', array(
             'name' => 'video_session_chapter_id_component_id',
             'local' => 'chapter_id',
             'foreign' => 'id',
             'foreignTable' => 'component',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('video_session', 'video_session_course_id_component_id', array(
             'name' => 'video_session_course_id_component_id',
             'local' => 'course_id',
             'foreign' => 'id',
             'foreignTable' => 'component',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->addIndex('video_session', 'video_session_profile_id', array(
             'fields' => 
             array(
              0 => 'profile_id',
             ),
             ));
        $this->addIndex('video_session', 'video_session_student_profile_id', array(
             'fields' => 
             array(
              0 => 'student_profile_id',
             ),
             ));
        $this->addIndex('video_session', 'video_session_chapter_id', array(
             'fields' => 
             array(
              0 => 'chapter_id',
             ),
             ));
        $this->addIndex('video_session', 'video_session_course_id', array(
             'fields' => 
             array(
              0 => 'course_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('video_session', 'video_session_profile_id_profile_id');
        $this->dropForeignKey('video_session', 'video_session_student_profile_id_profile_id');
        $this->dropForeignKey('video_session', 'video_session_chapter_id_component_id');
        $this->dropForeignKey('video_session', 'video_session_course_id_component_id');
        $this->removeIndex('video_session', 'video_session_profile_id', array(
             'fields' => 
             array(
              0 => 'profile_id',
             ),
             ));
        $this->removeIndex('video_session', 'video_session_student_profile_id', array(
             'fields' => 
             array(
              0 => 'student_profile_id',
             ),
             ));
        $this->removeIndex('video_session', 'video_session_chapter_id', array(
             'fields' => 
             array(
              0 => 'chapter_id',
             ),
             ));
        $this->removeIndex('video_session', 'video_session_course_id', array(
             'fields' => 
             array(
              0 => 'course_id',
             ),
             ));
    }
}