<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version26 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('profile_view_flash_message', 'profile_view_flash_message_profile_id_profile_id', array(
             'name' => 'profile_view_flash_message_profile_id_profile_id',
             'local' => 'profile_id',
             'foreign' => 'id',
             'foreignTable' => 'profile',
             ));
        $this->createForeignKey('profile_view_flash_message', 'profile_view_flash_message_flash_message_id_flash_message_id', array(
             'name' => 'profile_view_flash_message_flash_message_id_flash_message_id',
             'local' => 'flash_message_id',
             'foreign' => 'id',
             'foreignTable' => 'flash_message',
             ));
        $this->addIndex('profile_view_flash_message', 'profile_view_flash_message_profile_id', array(
             'fields' => 
             array(
              0 => 'profile_id',
             ),
             ));
        $this->addIndex('profile_view_flash_message', 'profile_view_flash_message_flash_message_id', array(
             'fields' => 
             array(
              0 => 'flash_message_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('profile_view_flash_message', 'profile_view_flash_message_profile_id_profile_id');
        $this->dropForeignKey('profile_view_flash_message', 'profile_view_flash_message_flash_message_id_flash_message_id');
        $this->removeIndex('profile_view_flash_message', 'profile_view_flash_message_profile_id', array(
             'fields' => 
             array(
              0 => 'profile_id',
             ),
             ));
        $this->removeIndex('profile_view_flash_message', 'profile_view_flash_message_flash_message_id', array(
             'fields' => 
             array(
              0 => 'flash_message_id',
             ),
             ));
    }
}