<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version23 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addIndex('predictive_learning_path', 'plp_unique_user_path_item', array(
             'fields' => 
             array(
              0 => 'profile_id',
              1 => 'course_id',
              2 => 'chapter_id',
              3 => 'lesson_id',
             ),
             'type' => 'unique',
             ));
    }

    public function down()
    {
        $this->removeIndex('predictive_learning_path', 'plp_unique_user_path_item', array(
             'fields' => 
             array(
              0 => 'profile_id',
              1 => 'course_id',
              2 => 'chapter_id',
              3 => 'lesson_id',
             ),
             'type' => 'unique',
             ));
    }
}