<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version29 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('video_session', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'autoincrement' => '1',
              'length' => '8',
             ),
             'profile_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'student_profile_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'chapter_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'course_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'scheduled_for' => 
             array(
              'type' => 'timestamp',
              'length' => '',
             ),
             'title' => 
             array(
              'type' => 'string',
              'length' => '100',
             ),
             'description' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'status' => 
             array(
              'type' => 'enum',
              'values' => 
              array(
              0 => 'pending',
              1 => 'started',
              2 => 'ended',
              ),
              'default' => 'pending',
              'length' => '',
             ),
             'url' => 
             array(
              'type' => 'string',
              'length' => '400',
             ),
             'type' => 
             array(
              'type' => 'enum',
              'values' => 
              array(
              0 => 'class',
              1 => 'support',
              ),
              'length' => '',
             ),
             'platform' => 
             array(
              'type' => 'string',
              'length' => '50',
             ),
             'created_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'deleted_at' => 
             array(
              'notnull' => '',
              'type' => 'timestamp',
              'length' => '25',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('video_session');
    }
}