<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version22 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('predictive_learning_path', 'predictive_learning_path_profile_id_profile_id', array(
             'name' => 'predictive_learning_path_profile_id_profile_id',
             'local' => 'profile_id',
             'foreign' => 'id',
             'foreignTable' => 'profile',
             ));
        $this->createForeignKey('predictive_learning_path', 'predictive_learning_path_course_id_component_id', array(
             'name' => 'predictive_learning_path_course_id_component_id',
             'local' => 'course_id',
             'foreign' => 'id',
             'foreignTable' => 'component',
             ));
        $this->createForeignKey('predictive_learning_path', 'predictive_learning_path_chapter_id_component_id', array(
             'name' => 'predictive_learning_path_chapter_id_component_id',
             'local' => 'chapter_id',
             'foreign' => 'id',
             'foreignTable' => 'component',
             ));
        $this->createForeignKey('predictive_learning_path', 'predictive_learning_path_lesson_id_component_id', array(
             'name' => 'predictive_learning_path_lesson_id_component_id',
             'local' => 'lesson_id',
             'foreign' => 'id',
             'foreignTable' => 'component',
             ));
        $this->addIndex('predictive_learning_path', 'predictive_learning_path_profile_id', array(
             'fields' => 
             array(
              0 => 'profile_id',
             ),
             ));
        $this->addIndex('predictive_learning_path', 'predictive_learning_path_course_id', array(
             'fields' => 
             array(
              0 => 'course_id',
             ),
             ));
        $this->addIndex('predictive_learning_path', 'predictive_learning_path_chapter_id', array(
             'fields' => 
             array(
              0 => 'chapter_id',
             ),
             ));
        $this->addIndex('predictive_learning_path', 'predictive_learning_path_lesson_id', array(
             'fields' => 
             array(
              0 => 'lesson_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('predictive_learning_path', 'predictive_learning_path_profile_id_profile_id');
        $this->dropForeignKey('predictive_learning_path', 'predictive_learning_path_course_id_component_id');
        $this->dropForeignKey('predictive_learning_path', 'predictive_learning_path_chapter_id_component_id');
        $this->dropForeignKey('predictive_learning_path', 'predictive_learning_path_lesson_id_component_id');
        $this->removeIndex('predictive_learning_path', 'predictive_learning_path_profile_id', array(
             'fields' => 
             array(
              0 => 'profile_id',
             ),
             ));
        $this->removeIndex('predictive_learning_path', 'predictive_learning_path_course_id', array(
             'fields' => 
             array(
              0 => 'course_id',
             ),
             ));
        $this->removeIndex('predictive_learning_path', 'predictive_learning_path_chapter_id', array(
             'fields' => 
             array(
              0 => 'chapter_id',
             ),
             ));
        $this->removeIndex('predictive_learning_path', 'predictive_learning_path_lesson_id', array(
             'fields' => 
             array(
              0 => 'lesson_id',
             ),
             ));
    }
}