<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version24 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('group_sub_group', 'group_sub_group_parent_id_groups_id', array(
             'name' => 'group_sub_group_parent_id_groups_id',
             'local' => 'parent_id',
             'foreign' => 'id',
             'foreignTable' => 'groups',
             ));
        $this->createForeignKey('group_sub_group', 'group_sub_group_child_id_groups_id', array(
             'name' => 'group_sub_group_child_id_groups_id',
             'local' => 'child_id',
             'foreign' => 'id',
             'foreignTable' => 'groups',
             ));
        $this->createForeignKey('groups', 'groups_creator_id_profile_id', array(
             'name' => 'groups_creator_id_profile_id',
             'local' => 'creator_id',
             'foreign' => 'id',
             'foreignTable' => 'profile',
             ));
        $this->addIndex('group_sub_group', 'group_sub_group_parent_id', array(
             'fields' => 
             array(
              0 => 'parent_id',
             ),
             ));
        $this->addIndex('group_sub_group', 'group_sub_group_child_id', array(
             'fields' => 
             array(
              0 => 'child_id',
             ),
             ));
        $this->addIndex('groups', 'groups_creator_id', array(
             'fields' => 
             array(
              0 => 'creator_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('group_sub_group', 'group_sub_group_parent_id_groups_id');
        $this->dropForeignKey('group_sub_group', 'group_sub_group_child_id_groups_id');
        $this->dropForeignKey('groups', 'groups_creator_id_profile_id');
        $this->removeIndex('group_sub_group', 'group_sub_group_parent_id', array(
             'fields' => 
             array(
              0 => 'parent_id',
             ),
             ));
        $this->removeIndex('group_sub_group', 'group_sub_group_child_id', array(
             'fields' => 
             array(
              0 => 'child_id',
             ),
             ));
        $this->removeIndex('groups', 'groups_creator_id', array(
             'fields' => 
             array(
              0 => 'creator_id',
             ),
             ));
    }
}