<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version24 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('profile', 'avatar', 'varchar', '100', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('profile', 'avatar');
    }
}