<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version40 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('profile', 'current_module', 'varchar', '50', array(
             ));
        $this->addColumn('profile', 'current_action', 'varchar', '50', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('profile', 'current_module');
        $this->removeColumn('profile', 'current_action');
    }
}