<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version34 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('notification', 'notification_notification_action_id_notification_action_id', array(
             'name' => 'notification_notification_action_id_notification_action_id',
             'local' => 'notification_action_id',
             'foreign' => 'id',
             'foreignTable' => 'notification_action',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('video_session_participant', 'video_session_participant_profile_id_profile_id', array(
             'name' => 'video_session_participant_profile_id_profile_id',
             'local' => 'profile_id',
             'foreign' => 'id',
             'foreignTable' => 'profile',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('video_session_participant', 'video_session_participant_video_session_id_video_session_id', array(
             'name' => 'video_session_participant_video_session_id_video_session_id',
             'local' => 'video_session_id',
             'foreign' => 'id',
             'foreignTable' => 'video_session',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->addIndex('notification', 'notification_notification_action_id', array(
             'fields' =>
             array(
              0 => 'notification_action_id',
             ),
             ));
        $this->addIndex('video_session_participant', 'video_session_participant_profile_id', array(
             'fields' =>
             array(
              0 => 'profile_id',
             ),
             ));
        $this->addIndex('video_session_participant', 'video_session_participant_video_session_id', array(
             'fields' =>
             array(
              0 => 'video_session_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('notification', 'notification_notification_action_id_notification_action_id');
        $this->dropForeignKey('video_session_participant', 'video_session_participant_profile_id_profile_id');
        $this->dropForeignKey('video_session_participant', 'video_session_participant_video_session_id_video_session_id');
        $this->removeIndex('notification', 'notification_notification_action_id', array(
             'fields' =>
             array(
              0 => 'notification_action_id',
             ),
             ));
        $this->removeIndex('video_session_participant', 'video_session_participant_profile_id', array(
             'fields' =>
             array(
              0 => 'profile_id',
             ),
             ));
        $this->removeIndex('video_session_participant', 'video_session_participant_video_session_id', array(
             'fields' =>
             array(
              0 => 'video_session_id',
             ),
             ));
    }
}