<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version26 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('mail_message', 'mail_message_profile_id_profile_id', array(
             'name' => 'mail_message_profile_id_profile_id',
             'local' => 'profile_id',
             'foreign' => 'id',
             'foreignTable' => 'profile',
             ));
        $this->addIndex('mail_message', 'mail_message_profile_id', array(
             'fields' => 
             array(
              0 => 'profile_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('mail_message', 'mail_message_profile_id_profile_id');
        $this->removeIndex('mail_message', 'mail_message_profile_id', array(
             'fields' => 
             array(
              0 => 'profile_id',
             ),
             ));
    }
}