<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version44 extends Doctrine_Migration_Base
{
    public function up()
    {
        $q = Doctrine_Manager::getInstance()->getCurrentConnection();
        
        //learning path view
        $query = "CREATE VIEW view_learning_path AS
          select c1.id as course_id, c1.name as course_name, 
          c2.id as chapter_id, c2.name as chapter_name,
          c3.id as lesson_id, c3.name as lesson_name,
          c4.id as resource_id, c4.name as resource_name

          from component c1 inner join learning_path lp1 on c1.id = lp1.parent_id inner join component c2 on c2.id = lp1.child_id inner join learning_path lp2 on lp1.child_id = lp2.parent_id inner join component c3 on lp2.child_id = c3.id inner join learning_path lp3 on lp2.child_id = lp3.parent_id inner join
          component c4 on lp3.child_id = c4.id

          WHERE c1.type = 'Course' AND
          c2.type = 'Chapter' AND
          c3.type = 'Lesson' AND
          c4.type = 'Resource'
        ";
        $q->execute($query);

        //course has chapter
        $query = "CREATE VIEW view_course_has_chapter AS
          SELECT c1.id AS course_id, c2.id AS chapter_id, lp1.enabled as enabled
          FROM component c1
          INNER JOIN learning_path lp1 ON c1.id = lp1.parent_id
          INNER JOIN component c2 ON c2.id = lp1.child_id
          WHERE c1.type =  'Course'
          AND c2.type =  'Chapter'
        ";
        $q->execute($query);

        
        //chapter has lesson
        $query = "CREATE VIEW view_chapter_has_lesson AS
          SELECT c1.id AS chapter_id, c2.id AS lesson_id, lp1.enabled as enabled
          FROM component c1
          INNER JOIN learning_path lp1 ON c1.id = lp1.parent_id
          INNER JOIN component c2 ON c2.id = lp1.child_id
          WHERE c1.type =  'Chapter'
          AND c2.type =  'Lesson'
        ";
        $q->execute($query);

        //lesson has resource
        $query = "CREATE VIEW view_lesson_has_resource AS
          SELECT c1.id AS lesson_id, c2.id AS resource_id, lp1.enabled as enabled
          FROM component c1
          INNER JOIN learning_path lp1 ON c1.id = lp1.parent_id
          INNER JOIN component c2 ON c2.id = lp1.child_id
          WHERE c1.type =  'Lesson'
          AND c2.type =  'Resource'
        ";
        $q->execute($query);
    }

    public function down()
    {
      $q = Doctrine_Manager::getInstance()->getCurrentConnection();
      $q->execute("DROP VIEW view_learning_path");
      $q->execute("DROP VIEW view_course_has_chapter");
      $q->execute("DROP VIEW view_chapter_has_lesson");
      $q->execute("DROP VIEW view_lesson_has_resource");
    }
}