<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version41 extends Doctrine_Migration_Base
{
    public function up()
    {
	$this->addColumn('video_session', 'visibility', 'enum', '', array(

             'values' => 

             array(

              0 => 'public',

              1 => 'private',

             ),

             'default' => 'public',

        ));
    }

    public function down()
    {

    }
}
