<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version46 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('time_view_component_by_day', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'profile_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'course_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'chapter_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'lesson_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'resource_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'type' => 
             array(
              'type' => 'string',
              'length' => '',
             ),
             'day' => 
             array(
              'type' => 'date',
              'length' => '25',
             ),
             'time_view' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
        $this->addColumn('profile_component_completed_status', 'time_view', 'integer', '8', array(
             ));
    }

    public function down()
    {
        $this->dropTable('time_view_component_by_day');
        $this->removeColumn('profile_component_completed_status', 'time_view');
    }
}