<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version36 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->changeColumn('sf_guard_forgot_password', 'id', 'integer', '8', array(
             'autoincrement' => '1',
             'primary' => '1',
             ));
        $this->changeColumn('sf_guard_forgot_password', 'user_id', 'integer', '8', array(
             'notnull' => '1',
             ));
        $this->changeColumn('sf_guard_forgot_password', 'unique_key', 'string', '255', array(
             ));
        $this->changeColumn('sf_guard_forgot_password', 'expires_at', 'timestamp', '25', array(
             'notnull' => '1',
             ));
        $this->changeColumn('sf_guard_forgot_password', 'created_at', 'timestamp', '25', array(
             'notnull' => '1',
             ));
        $this->changeColumn('sf_guard_forgot_password', 'updated_at', 'timestamp', '25', array(
             'notnull' => '1',
             ));
        $this->changeColumn('sf_guard_group', 'id', 'integer', '8', array(
             'autoincrement' => '1',
             'primary' => '1',
             ));
        $this->changeColumn('sf_guard_group', 'name', 'string', '255', array(
             'unique' => '1',
             ));
        $this->changeColumn('sf_guard_group', 'description', 'string', '1000', array(
             ));
        $this->changeColumn('sf_guard_group', 'created_at', 'timestamp', '25', array(
             'notnull' => '1',
             ));
        $this->changeColumn('sf_guard_group', 'updated_at', 'timestamp', '25', array(
             'notnull' => '1',
             ));
        $this->changeColumn('sf_guard_group_permission', 'group_id', 'integer', '8', array(
             'primary' => '1',
             ));
        $this->changeColumn('sf_guard_group_permission', 'permission_id', 'integer', '8', array(
             'primary' => '1',
             ));
        $this->changeColumn('sf_guard_group_permission', 'created_at', 'timestamp', '25', array(
             'notnull' => '1',
             ));
        $this->changeColumn('sf_guard_group_permission', 'updated_at', 'timestamp', '25', array(
             'notnull' => '1',
             ));
        $this->changeColumn('sf_guard_permission', 'id', 'integer', '8', array(
             'autoincrement' => '1',
             'primary' => '1',
             ));
        $this->changeColumn('sf_guard_permission', 'name', 'string', '255', array(
             'unique' => '1',
             ));
        $this->changeColumn('sf_guard_permission', 'description', 'string', '1000', array(
             ));
        $this->changeColumn('sf_guard_permission', 'created_at', 'timestamp', '25', array(
             'notnull' => '1',
             ));
        $this->changeColumn('sf_guard_permission', 'updated_at', 'timestamp', '25', array(
             'notnull' => '1',
             ));
        $this->changeColumn('sf_guard_remember_key', 'id', 'integer', '8', array(
             'autoincrement' => '1',
             'primary' => '1',
             ));
        $this->changeColumn('sf_guard_remember_key', 'user_id', 'integer', '8', array(
             ));
        $this->changeColumn('sf_guard_remember_key', 'remember_key', 'string', '32', array(
             ));
        $this->changeColumn('sf_guard_remember_key', 'ip_address', 'string', '50', array(
             ));
        $this->changeColumn('sf_guard_remember_key', 'created_at', 'timestamp', '25', array(
             'notnull' => '1',
             ));
        $this->changeColumn('sf_guard_remember_key', 'updated_at', 'timestamp', '25', array(
             'notnull' => '1',
             ));
        $this->changeColumn('sf_guard_user', 'id', 'integer', '8', array(
             'autoincrement' => '1',
             'primary' => '1',
             ));
        $this->changeColumn('sf_guard_user', 'first_name', 'string', '255', array(
             ));
        $this->changeColumn('sf_guard_user', 'last_name', 'string', '255', array(
             ));
        $this->changeColumn('sf_guard_user', 'email_address', 'string', '255', array(
             'notnull' => '1',
             'unique' => '1',
             ));
        $this->changeColumn('sf_guard_user', 'username', 'string', '128', array(
             'notnull' => '1',
             'unique' => '1',
             ));
        $this->changeColumn('sf_guard_user', 'algorithm', 'string', '128', array(
             'default' => 'sha1',
             'notnull' => '1',
             ));
        $this->changeColumn('sf_guard_user', 'salt', 'string', '128', array(
             ));
        $this->changeColumn('sf_guard_user', 'password', 'string', '128', array(
             ));
        $this->changeColumn('sf_guard_user', 'is_active', 'boolean', '25', array(
             'default' => '1',
             ));
        $this->changeColumn('sf_guard_user', 'is_super_admin', 'boolean', '25', array(
             'default' => '0',
             ));
        $this->changeColumn('sf_guard_user', 'last_login', 'timestamp', '25', array(
             ));
        $this->changeColumn('sf_guard_user', 'created_at', 'timestamp', '25', array(
             'notnull' => '1',
             ));
        $this->changeColumn('sf_guard_user', 'updated_at', 'timestamp', '25', array(
             'notnull' => '1',
             ));
        $this->changeColumn('sf_guard_user_group', 'user_id', 'integer', '8', array(
             'primary' => '1',
             ));
        $this->changeColumn('sf_guard_user_group', 'group_id', 'integer', '8', array(
             'primary' => '1',
             ));
        $this->changeColumn('sf_guard_user_group', 'created_at', 'timestamp', '25', array(
             'notnull' => '1',
             ));
        $this->changeColumn('sf_guard_user_group', 'updated_at', 'timestamp', '25', array(
             'notnull' => '1',
             ));
        $this->changeColumn('sf_guard_user_permission', 'user_id', 'integer', '8', array(
             'primary' => '1',
             ));
        $this->changeColumn('sf_guard_user_permission', 'permission_id', 'integer', '8', array(
             'primary' => '1',
             ));
        $this->changeColumn('sf_guard_user_permission', 'created_at', 'timestamp', '25', array(
             'notnull' => '1',
             ));
        $this->changeColumn('sf_guard_user_permission', 'updated_at', 'timestamp', '25', array(
             'notnull' => '1',
             ));
    }

    public function down()
    {

    }
}