<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version43 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('video_session', 'scheduled_end', 'timestamp', '', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('video_session', 'scheduled_end');
    }
}