<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version45 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('profile', 'culture', 'varchar', '20', array(
             ));
        $this->addColumn('profile', 'timezone', 'varchar', '20', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('profile', 'culture');
        $this->removeColumn('profile', 'timezone');
    }
}