<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version48 extends Doctrine_Migration_Base
{
    public function up()
    {
        $q = Doctrine_Manager::getInstance()->getCurrentConnection();
        // course
        $query = "
        UPDATE profile_component_completed_status pccs, (
            SELECT                                                                                   
                l.profile_id,
                l.course_id,
                SUM(TIME_TO_SEC(l.updated_at) - TIME_TO_SEC(l.created_at)) AS time_view
            FROM log_view_component l 
            GROUP BY   
                      l.profile_id,
                      l.course_id) l 
            SET pccs.time_view = l.time_view 
          WHERE pccs.profile_id = l.profile_id
            AND pccs.component_id = l.course_id    
        ";
        $q->execute($query);
        // chapter
        $query = "
        UPDATE profile_component_completed_status pccs, (
            SELECT                                                                                   
                l.profile_id,
                l.chapter_id,
                SUM(TIME_TO_SEC(l.updated_at) - TIME_TO_SEC(l.created_at)) AS time_view
            FROM log_view_component l 
            GROUP BY   
                      l.profile_id,
                      l.chapter_id) l 
            SET pccs.time_view = l.time_view 
          WHERE pccs.profile_id = l.profile_id
            AND pccs.component_id = l.chapter_id
        ";
        $q->execute($query);
        //lesson
        $query = "
        UPDATE profile_component_completed_status pccs, (
            SELECT                                                                                   
                l.profile_id,
                l.lesson_id,
                SUM(TIME_TO_SEC(l.updated_at) - TIME_TO_SEC(l.created_at)) AS time_view
            FROM log_view_component l 
            GROUP BY   
                      l.profile_id,
                      l.lesson_id) l 
            SET pccs.time_view = l.time_view 
          WHERE pccs.profile_id = l.profile_id
            AND pccs.component_id = l.lesson_id
        ";
        $q->execute($query);
        //resource
        $query = "
        UPDATE profile_component_completed_status pccs, (
            SELECT                                                                                   
                l.profile_id,
                l.resource_id,
                SUM(TIME_TO_SEC(l.updated_at) - TIME_TO_SEC(l.created_at)) AS time_view
            FROM log_view_component l 
            GROUP BY   
                      l.profile_id,
                      l.resource_id) l 
            SET pccs.time_view = l.time_view 
          WHERE pccs.profile_id = l.profile_id
                AND pccs.component_id = l.resource_id
        ";
    }

    public function down()
    {
        
    }
}