<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version42 extends Doctrine_Migration_Base
{
    public function up()
    {
        // $this->addColumn('college', 'style', 'string', '', array(
        //      ));
    }

    public function down()
    {
        $this->removeColumn('college', 'style');
    }
}