<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version47 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('time_view_component_by_day', 'time_view_component_by_day_course_id_component_id', array(
             'name' => 'time_view_component_by_day_course_id_component_id',
             'local' => 'course_id',
             'foreign' => 'id',
             'foreignTable' => 'component',
             ));
        $this->createForeignKey('time_view_component_by_day', 'time_view_component_by_day_chapter_id_component_id', array(
             'name' => 'time_view_component_by_day_chapter_id_component_id',
             'local' => 'chapter_id',
             'foreign' => 'id',
             'foreignTable' => 'component',
             ));
        $this->createForeignKey('time_view_component_by_day', 'time_view_component_by_day_lesson_id_component_id', array(
             'name' => 'time_view_component_by_day_lesson_id_component_id',
             'local' => 'lesson_id',
             'foreign' => 'id',
             'foreignTable' => 'component',
             ));
        $this->createForeignKey('time_view_component_by_day', 'time_view_component_by_day_resource_id_component_id', array(
             'name' => 'time_view_component_by_day_resource_id_component_id',
             'local' => 'resource_id',
             'foreign' => 'id',
             'foreignTable' => 'component',
             ));
        $this->createForeignKey('time_view_component_by_day', 'time_view_component_by_day_profile_id_profile_id', array(
             'name' => 'time_view_component_by_day_profile_id_profile_id',
             'local' => 'profile_id',
             'foreign' => 'id',
             'foreignTable' => 'profile',
             ));
        $this->addIndex('time_view_component_by_day', 'time_view_component_by_day_course_id', array(
             'fields' => 
             array(
              0 => 'course_id',
             ),
             ));
        $this->addIndex('time_view_component_by_day', 'time_view_component_by_day_chapter_id', array(
             'fields' => 
             array(
              0 => 'chapter_id',
             ),
             ));
        $this->addIndex('time_view_component_by_day', 'time_view_component_by_day_lesson_id', array(
             'fields' => 
             array(
              0 => 'lesson_id',
             ),
             ));
        $this->addIndex('time_view_component_by_day', 'time_view_component_by_day_resource_id', array(
             'fields' => 
             array(
              0 => 'resource_id',
             ),
             ));
        $this->addIndex('time_view_component_by_day', 'time_view_component_by_day_profile_id', array(
             'fields' => 
             array(
              0 => 'profile_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('time_view_component_by_day', 'time_view_component_by_day_course_id_component_id');
        $this->dropForeignKey('time_view_component_by_day', 'time_view_component_by_day_chapter_id_component_id');
        $this->dropForeignKey('time_view_component_by_day', 'time_view_component_by_day_lesson_id_component_id');
        $this->dropForeignKey('time_view_component_by_day', 'time_view_component_by_day_resource_id_component_id');
        $this->dropForeignKey('time_view_component_by_day', 'time_view_component_by_day_profile_id_profile_id');
        $this->removeIndex('time_view_component_by_day', 'time_view_component_by_day_course_id', array(
             'fields' => 
             array(
              0 => 'course_id',
             ),
             ));
        $this->removeIndex('time_view_component_by_day', 'time_view_component_by_day_chapter_id', array(
             'fields' => 
             array(
              0 => 'chapter_id',
             ),
             ));
        $this->removeIndex('time_view_component_by_day', 'time_view_component_by_day_lesson_id', array(
             'fields' => 
             array(
              0 => 'lesson_id',
             ),
             ));
        $this->removeIndex('time_view_component_by_day', 'time_view_component_by_day_resource_id', array(
             'fields' => 
             array(
              0 => 'resource_id',
             ),
             ));
        $this->removeIndex('time_view_component_by_day', 'time_view_component_by_day_profile_id', array(
             'fields' => 
             array(
              0 => 'profile_id',
             ),
             ));
    }
}