<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version50 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('exercise_has_exercise_question', 'eeei_1', array(
             'name' => 'eeei_1',
             'local' => 'exercise_parent_question_id',
             'foreign' => 'id',
             'foreignTable' => 'exercise_question',
             ));
        $this->addIndex('exercise_has_exercise_question', 'exercise_has_exercise_question_exercise_parent_question_id', array(
             'fields' => 
             array(
              0 => 'exercise_parent_question_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('exercise_has_exercise_question', 'eeei_1');
        $this->removeIndex('exercise_has_exercise_question', 'exercise_has_exercise_question_exercise_parent_question_id', array(
             'fields' => 
             array(
              0 => 'exercise_parent_question_id',
             ),
             ));
    }
}