<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version51 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->changeColumn('profile', 'timezone', 'varchar', '50', array(
             ));
    }

    public function down()
    {

    }
}