<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version49 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('exercise_has_exercise_question', 'exercise_parent_question_id', 'integer', '8', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('exercise_has_exercise_question', 'exercise_parent_question_id');
    }
}