<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version57 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('profile', 'country', 'varchar', '20', array(
             ));
        $this->addColumn('profile', 'district', 'varchar', '30', array(
             ));
        $this->addColumn('profile', 'institution', 'varchar', '50', array(
             ));
        $this->addColumn('profile', 'local_id_type', 'varchar', '20', array(
             ));
        $this->addColumn('profile', 'local_id', 'varchar', '50', array(
             ));
        $this->changeColumn('profile', 'nickname', 'varchar', '60', array(
             ));
        $this->changeColumn('profile', 'first_name', 'varchar', '60', array(
             ));
        $this->changeColumn('profile', 'last_name', 'varchar', '60', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('profile', 'country');
        $this->removeColumn('profile', 'district');
        $this->removeColumn('profile', 'institution');
        $this->removeColumn('profile', 'local_id_type');
        $this->removeColumn('profile', 'local_id');
    }
}