<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version58 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('profile', 'phone', 'varchar', '50', array(
             ));
        $this->addColumn('profile', 'mobile_phone', 'varchar', '50', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('profile', 'phone');
        $this->removeColumn('profile', 'mobile_phone');
    }
}