<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version53 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('profile_learning_path', 'pppi', array(
             'name' => 'pppi',
             'local' => 'profile_learning_path_status_id',
             'foreign' => 'id',
             'foreignTable' => 'profile_learning_path_status',
             ));
        $this->addIndex('profile_learning_path', 'profile_learning_path_profile_learning_path_status_id', array(
             'fields' => 
             array(
              0 => 'profile_learning_path_status_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('profile_learning_path', 'pppi');
        $this->removeIndex('profile_learning_path', 'profile_learning_path_profile_learning_path_status_id', array(
             'fields' => 
             array(
              0 => 'profile_learning_path_status_id',
             ),
             ));
    }
}