<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version56 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->changeColumn('profile_learning_path', 'profile_learning_path_status_id', 'integer', '8', array(
             'default' => '1',
             ));
    }

    public function down()
    {

    }
}