<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version52 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('profile_learning_path_status', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'autoincrement' => '1',
              'length' => '8',
             ),
             'name' => 
             array(
              'type' => 'varchar',
              'length' => '100',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
        $this->addColumn('profile_learning_path', 'profile_learning_path_status_id', 'integer', '8', array(
             ));
        $this->changeColumn('profile', 'timezone', 'varchar', '50', array(
             ));
    }

    public function down()
    {
        $this->dropTable('profile_learning_path_status');
        $this->removeColumn('profile_learning_path', 'profile_learning_path_status_id');
    }
}