<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version59 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('profile_component_completed_status', 'avg_note', 'float', '', array(
             ));
        $this->addColumn('profile_component_completed_status', 'attemps', 'integer', '8', array(
             ));
        $this->addColumn('profile_component_completed_status', 'approved_date', 'date', '25', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('profile_component_completed_status', 'avg_note');
        $this->removeColumn('profile_component_completed_status', 'attemps');
        $this->removeColumn('profile_component_completed_status', 'approved_date');
    }
}