<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version61 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('profile_component_completed_status', 'note', 'float', '', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('profile_component_completed_status', 'note');
    }
}