<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version65 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('college', 'logout_url', 'string', '', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('college', 'logout_url');
    }
}