<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version72 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('profile', 'profile_master_group_id_groups_id', array(
             'name' => 'profile_master_group_id_groups_id',
             'local' => 'master_group_id',
             'foreign' => 'id',
             'foreignTable' => 'groups',
             ));
        $this->createForeignKey('profile_has_group', 'profile_has_group_profile_id_profile_id', array(
             'name' => 'profile_has_group_profile_id_profile_id',
             'local' => 'profile_id',
             'foreign' => 'id',
             'foreignTable' => 'profile',
             ));
        $this->addIndex('profile', 'profile_master_group_id', array(
             'fields' => 
             array(
              0 => 'master_group_id',
             ),
             ));
        $this->addIndex('profile_has_group', 'profile_has_group_profile_id', array(
             'fields' => 
             array(
              0 => 'profile_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('profile', 'profile_master_group_id_groups_id');
        $this->dropForeignKey('profile_has_group', 'profile_has_group_profile_id_profile_id');
        $this->removeIndex('profile', 'profile_master_group_id', array(
             'fields' => 
             array(
              0 => 'master_group_id',
             ),
             ));
        $this->removeIndex('profile_has_group', 'profile_has_group_profile_id', array(
             'fields' => 
             array(
              0 => 'profile_id',
             ),
             ));
    }
}