<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version76 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('flash_message', 'mandatory', 'boolean', '25', array(
        	'default' => 0
             ));
    }

    public function down()
    {
        $this->removeColumn('flash_message', 'mandatory');
    }
}