<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version71 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('profile_has_group', array(
             'profile_id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'length' => '8',
             ),
             'group_id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'length' => '8',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'profile_id',
              1 => 'group_id',
             ),
             ));
        $this->addColumn('profile', 'master_group_id', 'integer', '8', array(
             ));
    }

    public function down()
    {
        $this->dropTable('profile_has_group');
        $this->removeColumn('profile', 'master_group_id');
    }
}