<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version66 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('flash_message', 'route', 'string', '', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('flash_message', 'route');
    }
}