<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version62 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('login_token', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'sf_guard_user_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'token' => 
             array(
              'type' => 'string',
              'length' => '',
             ),
             'valid_until' => 
             array(
              'type' => 'timestamp',
              'length' => '25',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('login_token');
    }
}