<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version63 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('login_token', 'login_token_sf_guard_user_id_sf_guard_user_id', array(
             'name' => 'login_token_sf_guard_user_id_sf_guard_user_id',
             'local' => 'sf_guard_user_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_user',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->addIndex('login_token', 'login_token_sf_guard_user_id', array(
             'fields' => 
             array(
              0 => 'sf_guard_user_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('login_token', 'login_token_sf_guard_user_id_sf_guard_user_id');
        $this->removeIndex('login_token', 'login_token_sf_guard_user_id', array(
             'fields' => 
             array(
              0 => 'sf_guard_user_id',
             ),
             ));
    }
}