<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version69 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('flash_message', 'flash_message_college_id_college_id', array(
             'name' => 'flash_message_college_id_college_id',
             'local' => 'college_id',
             'foreign' => 'id',
             'foreignTable' => 'college',
             ));
        $this->addIndex('flash_message', 'flash_message_college_id', array(
             'fields' => 
             array(
              0 => 'college_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('flash_message', 'flash_message_college_id_college_id');
        $this->removeIndex('flash_message', 'flash_message_college_id', array(
             'fields' => 
             array(
              0 => 'college_id',
             ),
             ));
    }
}