<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version46 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('calendar_event', 'tipo_ref', 'char', '5', array(
             ));
        $this->renameColumn( 'calendar_event', 'profile_id', 'ref_id' );
    }

    public function down()
    {
        $this->removeColumn('calendar_event', 'tipo_ref');
        $this->renameColumn( 'calendar_event', 'ref_id', 'profile_id' );
    }
}