<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version46 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->removeIndex('calendar_event', 'profile_id', array(
             'fields' => 
             array(
              0 => 'profile_id',
             ),
             ));
    }

    public function down()
    {
        $this->addIndex('calendar_event', 'profile_id', array(
             'fields' => 
             array(
              0 => 'profile_id',
             ),
             ));
    }
}