<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version45 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('calendar_event', 'address', 'string', '255', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('calendar_event', 'address');
    }
}