<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version47 extends Doctrine_Migration_Base
{
    public function up()
    {
        $q = Doctrine_Manager::getInstance()->getCurrentConnection();
        
        $query = "UPDATE kuepa.calendar_event as ce SET ce.ref_id = ce.profile_id;";
        $q->execute($query);
        
        $this->removeColumn('calendar_event', 'profile_id');
        
        $query = 'UPDATE kuepa.calendar_event as ce SET ce.tipo_ref = "PROFI";';
        $q->execute($query);
        
    }

    public function down()
    {
        
        $q = Doctrine_Manager::getInstance()->getCurrentConnection();
        
        $query = "UPDATE kuepa.calendar_event as ce SET ce.profile_id = ce.ref_id;";
        $q->execute($query);
        
        $this->removeColumn('calendar_event', 'ref_id');
        
        $query = 'UPDATE kuepa.calendar_event as ce SET ce.tipo_ref = "PROFI";';
        $q->execute($query);
        
    }
}