<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version79 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('learning_way_item', 'learning_way_item_learning_way_id_learning_way_id', array(
             'name' => 'learning_way_item_learning_way_id_learning_way_id',
             'local' => 'learning_way_id',
             'foreign' => 'id',
             'foreignTable' => 'learning_way',
             ));
        $this->createForeignKey('learning_way_item', 'learning_way_item_course_id_component_id', array(
             'name' => 'learning_way_item_course_id_component_id',
             'local' => 'course_id',
             'foreign' => 'id',
             'foreignTable' => 'component',
             ));
        $this->createForeignKey('learning_way_item', 'learning_way_item_chapter_id_component_id', array(
             'name' => 'learning_way_item_chapter_id_component_id',
             'local' => 'chapter_id',
             'foreign' => 'id',
             'foreignTable' => 'component',
             ));
        $this->createForeignKey('learning_way_item', 'learning_way_item_lesson_id_component_id', array(
             'name' => 'learning_way_item_lesson_id_component_id',
             'local' => 'lesson_id',
             'foreign' => 'id',
             'foreignTable' => 'component',
             ));
        $this->createForeignKey('profile_has_learning_way', 'profile_has_learning_way_profile_id_profile_id', array(
             'name' => 'profile_has_learning_way_profile_id_profile_id',
             'local' => 'profile_id',
             'foreign' => 'id',
             'foreignTable' => 'profile',
             ));
        $this->createForeignKey('profile_has_learning_way', 'profile_has_learning_way_learning_way_id_learning_way_id', array(
             'name' => 'profile_has_learning_way_learning_way_id_learning_way_id',
             'local' => 'learning_way_id',
             'foreign' => 'id',
             'foreignTable' => 'learning_way',
             ));
        $this->createForeignKey('profile_has_learning_way', 'profile_has_learning_way_learning_way_id_profile_id', array(
             'name' => 'profile_has_learning_way_learning_way_id_profile_id',
             'local' => 'learning_way_id',
             'foreign' => 'id',
             'foreignTable' => 'profile',
             ));
        $this->addIndex('learning_way_item', 'learning_way_item_learning_way_id', array(
             'fields' => 
             array(
              0 => 'learning_way_id',
             ),
             ));
        $this->addIndex('learning_way_item', 'learning_way_item_course_id', array(
             'fields' => 
             array(
              0 => 'course_id',
             ),
             ));
        $this->addIndex('learning_way_item', 'learning_way_item_chapter_id', array(
             'fields' => 
             array(
              0 => 'chapter_id',
             ),
             ));
        $this->addIndex('learning_way_item', 'learning_way_item_lesson_id', array(
             'fields' => 
             array(
              0 => 'lesson_id',
             ),
             ));
        $this->addIndex('profile_has_learning_way', 'profile_has_learning_way_profile_id', array(
             'fields' => 
             array(
              0 => 'profile_id',
             ),
             ));
        $this->addIndex('profile_has_learning_way', 'profile_has_learning_way_learning_way_id', array(
             'fields' => 
             array(
              0 => 'learning_way_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('learning_way_item', 'learning_way_item_learning_way_id_learning_way_id');
        $this->dropForeignKey('learning_way_item', 'learning_way_item_course_id_component_id');
        $this->dropForeignKey('learning_way_item', 'learning_way_item_chapter_id_component_id');
        $this->dropForeignKey('learning_way_item', 'learning_way_item_lesson_id_component_id');
        $this->dropForeignKey('profile_has_learning_way', 'profile_has_learning_way_profile_id_profile_id');
        $this->dropForeignKey('profile_has_learning_way', 'profile_has_learning_way_learning_way_id_learning_way_id');
        $this->dropForeignKey('profile_has_learning_way', 'profile_has_learning_way_learning_way_id_profile_id');
        $this->removeIndex('learning_way_item', 'learning_way_item_learning_way_id', array(
             'fields' => 
             array(
              0 => 'learning_way_id',
             ),
             ));
        $this->removeIndex('learning_way_item', 'learning_way_item_course_id', array(
             'fields' => 
             array(
              0 => 'course_id',
             ),
             ));
        $this->removeIndex('learning_way_item', 'learning_way_item_chapter_id', array(
             'fields' => 
             array(
              0 => 'chapter_id',
             ),
             ));
        $this->removeIndex('learning_way_item', 'learning_way_item_lesson_id', array(
             'fields' => 
             array(
              0 => 'lesson_id',
             ),
             ));
        $this->removeIndex('profile_has_learning_way', 'profile_has_learning_way_profile_id', array(
             'fields' => 
             array(
              0 => 'profile_id',
             ),
             ));
        $this->removeIndex('profile_has_learning_way', 'profile_has_learning_way_learning_way_id', array(
             'fields' => 
             array(
              0 => 'learning_way_id',
             ),
             ));
    }
}