<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version78 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('learning_way', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'autoincrement' => '1',
              'length' => '8',
             ),
             'name' => 
             array(
              'type' => 'string',
              'length' => '',
             ),
             'description' => 
             array(
              'type' => 'string',
              'length' => '',
             ),
             'created_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
        $this->createTable('learning_way_item', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'learning_way_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'course_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'chapter_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'lesson_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'position' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'created_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             ), array(
             'indexes' => 
             array(
              'dplp_unique_learning_path_item' => 
              array(
              'fields' => 
              array(
               0 => 'learning_way_id',
               1 => 'course_id',
               2 => 'chapter_id',
               3 => 'lesson_id',
              ),
              'type' => 'unique',
              ),
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
        $this->createTable('profile_has_learning_way', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'learning_way_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'profile_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('learning_way');
        $this->dropTable('learning_way_item');
        $this->dropTable('profile_has_learning_way');
    }
}