<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version81 extends Doctrine_Migration_Base
{
    public function up()
    {
        
        $this->addColumn('calendar_event', 'ref_id', 'integer', '8', array());
        $this->addColumn('calendar_event', 'tipo_ref', 'char', '5', array());
        $this->addColumn('calendar_event', 'address', 'string', '255', array());
        
    }

    public function down()
    {
        
        $this->addColumn('calendar_event', 'profile_id', 'integer', '8', array());
        $this->removeColumn('calendar_event', 'tipo_ref');
        $this->removeColumn('calendar_event', 'address');
        
    }
}