<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version80 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addIndex('profile_has_learning_way', 'plw_unique_user_learning_way', array(
             'fields' => 
             array(
              0 => 'profile_id',
              1 => 'learning_way_id',
             ),
             'type' => 'unique',
             ));
    }

    public function down()
    {
        $this->removeIndex('profile_has_learning_way', 'plw_unique_user_learning_way', array(
             'fields' => 
             array(
              0 => 'profile_id',
              1 => 'learning_way_id',
             ),
             'type' => 'unique',
             ));
    }
}