# Main user entity, sfGuardUser is only used to store basic user data and login credentials
Profile:
  tableName:                   profile
  actAs:
    Timestampable: ~
    SoftDelete: ~
  columns:
    sf_guard_user_id:          integer 
    nickname:                  varchar(20)
    first_name:                varchar(20)
    last_name:                 varchar(20)
    birthdate:                 date
    sex:                       { type: enum, values: [male, female] }
    valid_until:               date
  relations:
    sfGuardUser:               { class: sfGuardUser, onDelete: CASCADE, local: sf_guard_user_id, foreign: id, foreignType: one }
    Colleges:
      class: College
      refClass: ProfileCollege
      type: many
      local: profile_id
      foreign: college_id
      foreignAlias: Profiles
    Components:
      class: Component
      refClass: ProfileLearningPath
      type: many
      local: profile_id
      foreign: component_id
      foreignAlias: Profiles

ProfileLearningPath:
  columns:
    profile_id: {type: integer, primary: true}
    component_id: {type: integer, primary: true}
    deadline: { type: date }
    position: { type: integer, default: 0 }

ProfileCollege:
  columns:
    profile_id: {type: integer, primary: true}
    college_id: {type: integer, primary: true}

CollegeLearningPath:
  columns:
    college_id: {type: integer, primary: true}
    component_id: {type: integer, primary: true}

College:
  tableName: college
  columns:
    id: { type: integer, primary: true, autoincrement: true }
    name: varchar(255)
  relations:
    Components:
      class: Component
      refClass: CollegeLearningPath
      type: many
      local: college_id
      foreign: component_id
      foreignAlias: Colleges

Component:
  actAs:
    Timestampable: ~
    SoftDelete: ~
    # Versionable:
    #   versionColumn: version
    #   className: %CLASS%Version
    #   auditLog: true
  tableName: component
  columns:
    id: { type: integer, primary: true, autoincrement: true }
    node_id: integer
    name: varchar(255)
    thumbnail: varchar(255)
    description: text
    level: { type: enum, values: [beginner, intermediate, advance]}
    profile_id: { type: integer }
    color: { type: enum, values: [green, lightgreen, violet, red, purple, blue, lightblue, darkblue, orange]}
    duration: float
    deadline: { type: date }
  relations:
    Parents:
      class: Component
      refClass: LearningPath
      local: child_id
      foreign: parent_id
      type: many
    Children:
      class: Component
      refClass: LearningPath
      local: parent_id
      foreign: child_id
      type: many
    Author:
      class: Profile
      foreign: id
      local: profile_id
      type: one

Resource:
  inheritance:
    extends:          Component
    type: column_aggregation
    keyField: type
    keyValue: Resource
  relations:
    ResourceData:
      class: ResourceData
      local: id
      foreign: resource_id
      type: many
      foreignType: one
      foreignAlias: Resource

Course:
  inheritance:
    extends:          Component
    type: column_aggregation
    keyField: type
    keyValue: Course

Chapter:
  inheritance:
    extends:          Component
    type: column_aggregation
    keyField: type
    keyValue: Chapter

Lesson:
  inheritance:
    extends:          Component
    type: column_aggregation
    keyField: type
    keyValue: Lesson

LearningPath:
  columns:
    parent_id: integer
    child_id: integer
    position: integer
    enabled: {type: boolean, default: true}
  relations:
    Parent:
      class: Component
      local: parent_id
      foreign: id
      type: one
    Child:
      class: Component
      local: child_id
      foreign: id
      type: one

ResourceData:
  actAs:
    Timestampable: ~
    SoftDelete: ~
    # Versionable:
    #   versionColumn: version
    #   className: %CLASS%Version
    #   auditLog: true
  columns:
    id: { type: integer, primary: true, autoincrement: true }
    resource_id: { type: integer }
    position: {type: integer, default: 1}
    content: blob
    enabled: { type: boolean, notnull: true, default: true }
    tags: { type: string }
    profile_id: { type: integer }
    parent_id: { type: integer }
    duration: float
    level: { type: enum, values: [beginner, intermediate, advance]}
    word_count: { type: integer }
  relations:
    Author:
      class: Profile
      foreign: id
      local: profile_id
      type: one
    Notes:
      class: Note
      type: many
      local: id
      foreign: resource_id
      foreignType: one
      foreignAlias: Resource
    # CreatedFrom:
    #   class: ResourceData
    #   local: parent_id
    #   foreign: id
    #   type: one


ResourceDataDocument:
  columns: 
    document_type: { type: enum, values: [pdf, image, ppt] }
  inheritance:
    extends: ResourceData
    type: column_aggregation
    keyField: type
    keyValue: Document

ResourceDataText:
  inheritance:
    extends: ResourceData
    type: column_aggregation
    keyField: type
    keyValue: Text

ResourceDataVideo:
  columns: 
    video_type: { type: enum, values: [youtube, vimeo, embebed] }
    path: { type: string }
  inheritance:
    extends: ResourceData
    type: column_aggregation
    keyField: type
    keyValue: Video

ResourceDataEmbeddedWeb:
  inheritance:
    extends: ResourceData
    type: column_aggregation
    keyField: type
    keyValue: EmbeddedWeb

ResourceDataExercise:
  inheritance:
    extends: ResourceData
    type: column_aggregation
    keyField: type
    keyValue: Exercise

Exercise:
  actAs:
    Timestampable: ~
    SoftDelete: ~
  columns:
    id: { type: integer, primary: true, autoincrement: true }
    title: string(200)
    description: text
    type: string
    max_attemps: integer
    start_time: datetime
    end_time: datetime
    expired_time: integer
    random: integer
    results_disabled: boolean
  relations:
    Questions:
      class: ExerciseQuestion
      refClass: ExerciseHasExerciseQuestion
      local: exercise_id
      foreign: exercise_question_id
      type: many

ExerciseQuestion:
  actAs:
    Timestampable: ~
    SoftDelete: ~
  columns:
    id: { type: integer, primary: true, autoincrement: true }
    title: string(200)
    description: text
    value: integer
    type: string

ExerciseAnswer:
  actAs:
    Timestampable: ~
    SoftDelete: ~
  columns:
    id: { type: integer, primary: true, autoincrement: true }
    title: text
    comment: text
    value: integer
    correct: integer
    exercise_question_id: integer
  relations:
    Question:
      class: ExerciseQuestion
      local: exercise_question_id
      foreignAlias: Answers
      foreign: id
      type: one

ExerciseHasExerciseQuestion:
  columns:
    exercise_id: integer
    exercise_question_id: integer
    position: { type: integer, notnull: true, default: 1}
  relations:
    Exercise:
      local: exercise_id
      foreign: id
      type: one
    ExerciseQuestion:
      local: exercise_question_id
      foreign: id
      type: one

ExerciseAttemp:
  actAs:
    Timestampable:
      created:
        name: created_at
        type: timestamp
        format: Y-m-d H:i:s
      updated:
        disabled: true
  columns:
    profile_id: integer
    exercise_id: integer
    time_taken: timestamp
    value: float
    content: blob
  relations:
    ResourceData:
      local: exercise_id
      foreign: content
      type: many
    Exercise:
      local: exercise_id
      foreign: id
      type: one
    Profile:
      local: profile_id
      foreign: id

LogViewComponent:
  actAs:
    Timestampable: ~
  columns:
    profile_id: integer
    component_id: integer
    type: string
  relations:
    Component:
      local: component_id
      foreign: id
      type: one
    Profile:
      local: profile_id
      foreign: id

LogAccess:
  actAs:
    Timestampable: ~
  columns:
    profile_id: integer
  relations:
    Profile:
      local: profile_id
      foreign: id

Note:
  actAs:
    Timestampable: ~
  columns:
    id: { type: integer, primary: true, autoincrement: true }
    resource_id: integer
    profile_id: integer
    content: string
    privacy: string(20)
  relations:
    Resource:
      local: resource_id
      foreign: id
      type: one
    Profile:
      local: profile_id
      foreign: id

ProfileComponentCompletedStatus:
  columns:
    profile_id: {type: integer, primary: true}
    component_id: {type: integer, primary: true}
    completed_status: {type: integer}
    velocity_index: float
    completitud_index: float
    skill_index: float
    persistence_index: float
    effort_index: float
    efficiency_index: float
    learning_index: float
  relations:
    Component:
      local: component_id
      foreign: id
      type: one
    Profile:
      local: profile_id
      foreign: id

Message:
  actAs:
    Timestampable: ~
  columns:
    id: {type: integer, primary: true, autoincrement: true}
    author_id: {type: integer, notnull: true}
    subject: {type: string(255)}
    content: {type: string}
    parent_id: {type: integer}
  relations:
    Profile:
      type: one
      local: author_id
      foreign: id
    Recipients:
      class: MessageRecipient
      type: many
      local: id
      foreign: message_id
      foreignType: one
      foreignAlias: Message
    Root:
      class: Message
      type: one
      local: parent_id
      foreign: id

MessageRecipient:
  columns:
    id: {type: integer, primary: true, autoincrement: true}
    message_id: {type: integer, notnull: true}
    recipient_id: {type: integer, notnull: true}
    is_read: {type: boolean, notnull: true, default: false}
  relations:
    Recipient:
      class: Profile
      type: one
      local: recipient_id
      foreign: id
      foreignAlias: ReceivedMessages
      foreignType: many

CalendarEvent:
  actAs:
    Timestampable: ~
  columns:
    id: {type: integer, primary: true, autoincrement: true}
    profile_id: integer
    component_id: {type: integer}
    title: {type: string(255)}
    description: {type: string}
    start: {type: timestamp}
    end: {type: timestamp}
  relations:
    Profile:
      local: profile_id
      foreign: id

RegisterCode:
  columns:
    id: {type: string(50), primary: true}
    profile_id: integer
    valid_from: date
    valid_until: date
    valid_days: integer
    college_id: integer
    active: {type: boolean, default: false, notnull: true}
    in_use: {type: integer, default: 0, notnull: true}
  relations:
    Profile:
      local: profile_id
      foreign: id
    College:
      local: college_id
      foreign: id
    Course:
      refClass: RegisterCodeHasCourse
      local: register_code
      foreign: course_id
      type: many

RegisterCodeHasCourse:
  columns:
    register_code: {type: string(50), primary: true}
    course_id: {type: integer, primary: true}